(function () {
    function createRuntime({
        THREE,
        DEFAULT_PLAYER,
        TOTAL_INV_SIZE,
        BREATH_MAX,
        coarsePointer,
        noHover,
        touchCapable,
        PLAYER_HEIGHT,
    }) {
        return {
            constants: {
                DEFAULT_LOOK_SENSITIVITY: 10,
                DEFAULT_INTERACTION_REACH: 5,
                SWIM_SPEED_FACTOR: 0.58,
                SWIM_VERTICAL_SPEED: 0.1,
                SWIM_SINK_SPEED: -0.03,
                SWIM_SPRINT_MULTIPLIER: 1.25,
                BREATH_MAX,
                BREATH_DRAIN_PER_SEC: BREATH_MAX / 15,
                BREATH_REGEN_PER_SEC: BREATH_MAX / 4,
                DROWN_DAMAGE_INTERVAL_SEC: 1,
                AIR_POP_DURATION_SEC: 0.5,
                INVENTORY_ENTITY_UPDATE_INTERVAL_MS: 100,
                FLY_VERTICAL_SPEED: 0.24,
                PLAYER_EYE_HEIGHT_RATIO: 1.62 / 1.8,
                MOB_COLLISION_RADIUS: {
                    pig: 0.4,
                    wolf: 0.46,
                    panda: 0.56,
                    zombie: 0.42,
                    villager: 0.44,
                    gnome: 0.34,
                },
            },
            player: {
                velocity: new THREE.Vector3(),
                direction: new THREE.Vector3(),
                moveSpeed: DEFAULT_PLAYER.moveSpeed,
                baseMoveSpeed: DEFAULT_PLAYER.moveSpeed,
                sprintMultiplier: DEFAULT_PLAYER.sprintMultiplier,
                rotationSpeed: DEFAULT_PLAYER.rotationSpeed,
                isJumping: false,
                canMove: false,
                keys: {},
                health: DEFAULT_PLAYER.health,
                maxHealth: DEFAULT_PLAYER.maxHealth,
                fallStartY: 0,
                inAir: false,
                isMoving: false,
                isSwimming: false,
            },
            inventory: new Array(TOTAL_INV_SIZE).fill(null),
            selectedHotbarIndex: 0,
            isInventoryOpen: false,
            isCreativeMode: false,
            isCreativeMenuOpen: false,
            creativeCatalog: [],
            playerPrivileges: { fly: false, speed: false, noclip: false },
            isFlyActive: false,
            lastSpaceTapAt: 0,
            airState: {
                value: BREATH_MAX,
                drownTimerSec: 0,
                popTimerSec: 0,
                wasUnderLiquid: false,
            },
            mobileControls: {
                autoEnabled: coarsePointer || (touchCapable && noHover) || (touchCapable && window.innerWidth <= 1024),
                enabled: false,
                initialized: false,
                moveX: 0,
                moveY: 0,
                sprint: false,
                jump: false,
                joystickPointerId: null,
                worldTouchActive: false,
                worldTouchStartMs: 0,
                worldTouchPointerId: null,
                miningTimer: null,
                isMiningTouch: false,
                lookPointerId: null,
                lastLookX: 0,
                lastLookY: 0,
            },
            currentPlayerHeight: PLAYER_HEIGHT,
            cameraViewMode: 0,
            playerAvatar: null,
            playerAvatarParts: null,
            steveSkinTexture: null,
            steveSkinFailed: false,
            steveSkinReady: false,
            steveSkinLoadPromise: null,
            firstPersonHandEl: null,
            firstPersonHeldItemEl: null,
            inventorySkinRigEl: null,
            skinSystem: null,
            eatOverlayEl: null,
            eatItemEl: null,
            eatingAnimState: { active: false, timeMs: 0, durationMs: 0, itemId: 0, particleMs: 0 },
        };
    }

    window.SingleplayerPlayerCore = {
        createRuntime,
    };
})();
